create table weatherinfo
(
    id   bigint generated by default as identity,
    nx double,
    ny double,
    date varchar(8),
    time varchar(8),
    skycode int,
    ptyCode int,
    temp double,
    hum double
    primary key (id)
);

create table regioninfo
(
    id   bigint generated by default as identity,
    primary key (id)
);
